### PR TITLE
Update crd version

### PR DESCRIPTION
**Pull request by StrongMonkey**

### CODE REVIEW

**Comment by ibuildthecloud** [comment]
In order to accept this PR I think we need to change the CRD generate such that if no openapi schema is provided we just add the following schema.  Then this will continue to work with Rancher until we fix the CRDs in Rancher.
```
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            x-kubernetes-preserve-unknown-fields: true
          status:
            x-kubernetes-preserve-unknown-fields: true```

**Comment by ekristen** [comment]
@ibuildthecloud once this is accepted will wrangler defaults for CRD properties work or will that require an additional PR to work?

**Comment by ibuildthecloud** [comment]
@ekristen Defaults should work.

**Comment by StrongMonkey** [comment]
@ibuildthecloud Dummy schema is added to prevent pruning.

**Pull request merged**
