### PR TITLE
[WIP] Add back apiext v1beta1 support for upgrade scenarios

### PR DESCRIPTION
**Pull request by nickgerace**
## Relevant issues
- https://github.com/rancher/rancher/issues/33586
- https://github.com/rancher/rancher/issues/33112
- https://github.com/rancher/fleet/issues/451

## Description
This PR adds back apiext `v1beta1` support to generate `v1beta1` CRDs and to create them (relevant for Fleet and Rancher installing CRDs themselves). It does not do anything more. The apiext `v1beta1` CRD generation functionality was restored by comparing the commit before apiext was upgraded to `master`.

## Reasoning
Event though apiext CRD `v1beta1` is being removed in k8s 1.22.0, Rancher must handle upgrade scenarios from k8s <= 1.15.x clusters.

## Diffs Used for Reference
- https://github.com/rancher/wrangler/commit/74a27343c8e2f1463d2afa5a11413ef7bfdb096e
- https://github.com/rancher/wrangler/compare/70e0f56...master

## Technical Notes
- some copied functions may differ slightly from their apiext `v1` variants
  - this is because there have been many CRD changes since apiext was upgraded that are for `v1` CRDs
- D.R.Y was not strictly followed _because_ `v1beta1` functionality should not weight down `v1` usage
  - `v1beta1` CRDs are only meant to be used when _needed_
- design goal: do not change anything (or as little as possible) about how users create v1 CRDs (consumers should not even notice this change)
- this PR was created by "reverse engineering" the `v1beta1` `ToCustomResourceDefinition()` method from before the upgrade

### CODE REVIEW

**Comment by nickgerace** [comment]
All recent pushes have been cosmetic. This PR has remained the same in functionality since it was moved out of WIP.

**Review by kinarashah — COMMENTED** [review]
Reviewed based off https://github.com/rancher/wrangler/commit/74a27343c8e2f1463d2afa5a11413ef7bfdb096e. 
LGTM.

**Comment by nickgerace** [comment]
Spoke to @StrongMonkey. Going to try to write a v1 to v1beta1 converter instead. Leaving this PR up in case that effort yields inconsistent results.

**Comment by nickgerace** [comment]
Closing in favor of https://github.com/rancher/wrangler/pull/172

**Pull request closed without merging**
