### PR TITLE
update client-go to 0.28 and update resource lease lock

### PR DESCRIPTION
**Pull request by galal-hussein**
Kubernetes has removed support for ConfigMapsLeasesResourceLock in v1.28 and moved to LeasesResourceLock https://github.com/kubernetes/kubernetes/pull/117558

### CODE REVIEW

**Review by brandond — APPROVED** [review]
🤞🏻

**Review by cwayne18 — APPROVED** [review]

**Comment by brandond** [comment]
FYI this is a blocker for K3s and RKE2 1.28

**Review by KevinJoiner — APPROVED** [review]
Nice `ConfigMapsLeasesResourceLock` was causing a bug in my dev environment.

**Comment by cwayne18** [comment]
@cbron this is something we need to get RKE2/K3s 1.28.0 out, should we be merging this into master or would you prefer we create a branch or use `dev-2.8` for it?

**Comment by brandond** [comment]
This should go into master, and anything that needs to remain on 1.27 and earlier can use a branch.

Unfortunately this repo now has two branching strategies - one that follows the tag structure for this repo, and another that follows rancher release versions. That should probably be addressed before any further branching occurs.

**Comment by rmweir** [comment]
@brandond we're not using two branching strategies. You can disregard the release/v2.x branches. Branching strategy is described in the README:
```
Wrangler releases are not from the default branch. Instead they are from branches with the naming pattern release-MAJOR.MINOR. The default branch (i.e. master) is where changes initially go. This includes bug fixes and new features. Bug fixes are cherry-picked to release branches to be included in patch releases. When it's time to create a new minor or major release, a new release branch is created from the default branch.
```

**Comment by rmweir** [comment]
Merging and this will go into 2.1

**Comment by brandond** [comment]
@rmweir can we get rid of the old release/v2.x branches then? Both from here and from rancher/lasso?

**Pull request merged**
